version: "3.7"
volumes:
    wordpress:
        name: wordpress
        driver_opts:
            type: none
            o: bind
            device: /home/omillan/data/wordpress
    mysql:
        name: mysql
        driver_opts:
            type: none
            o: bind
            device: /home/omillan/data/mysql
    my_site_storage:
        name: wordpress
        driver_opts:
            type: none
            o: bind
            device: /home/omillan/data/my_site_storage

networks:
  one-net:
    name: one-net

services:
#nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    image: nginx 
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - one-net
    depends_on:
      - wordpress
      - my_site
#wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
    image: wordpress 
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - one-net
    depends_on:
      - mysql
#mysql
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - one-net
#ftp
  ftp:
    container_name: ftp
    build: 
      context: ./ftp
    image: ftp
    restart: always
    ports:
      - 21000:21000
      - "21:21"
    volumes:
      - wordpress:/home/omillan
    networks:
      - one-net
    depends_on:
      - wordpress
#adminer
  adminer:
    container_name: adminer
    build: 
      context: ./adminer
    image: adminer
    restart: always
    networks:
      - one-net
    depends_on:
      - wordpress
#redis
  redis:
    container_name: redis
    build: 
      context: ./redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - one-net
#my_site
  my_site:
    container_name: my_site
    build:
      context: ./my_site
    image: my_site
    restart: always
    networks:
      - one-net
#storage-server for my_site
  storage:
    container_name: storage
    build:
      context: ./storage
    image: storage
    restart: always
    volumes:
      - my_site_storage:/var/www/storage
    networks:
      - one-net
