version: "3"
#volumes
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/omillan/data/wordpress
      o: bind
  mysql:
    name: mysql
    driver: local
    driver_opts:
      type: none
      device: /home/omillan/data/mysql
      o: bind
  my_site_storage:
    name: my_site_storage
    driver: local
    driver_opts:
      type: none
      device: /home/omillan/data/my_site_storage
      o: bind

#network
networks:
  one-net:
    name: one-net

#servisec
services:
#nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    image: nginx 
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - one-net
    depends_on:
      - wordpress
      - my_site
#wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
    image: wordpress 
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - one-net
    depends_on:
      - mysql
    environment:
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_USER_PASSWORD=${WP_DB_USER_PASSWORD}
      - WP_DB_HOST=${WP_DB_HOST}

#mysql
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - one-net
    environment:
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_USER_PASSWORD=${MYSQL_DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DOCKER_NETWORK=${DOCKER_NETWORK}
#ftp
  ftp:
    container_name: ftp
    build: 
      context: ./ftp
    image: ftp
    restart: always
    ports:
      - 21000:21000
      - "21:21"
    volumes:
      - wordpress:/home/omillan
    networks:
      - one-net
    depends_on:
      - wordpress
#adminer
  adminer:
    container_name: adminer
    build: 
      context: ./adminer
    image: adminer
    restart: always
    networks:
      - one-net
    depends_on:
      - wordpress
#redis
  redis:
    container_name: redis
    build: 
      context: ./redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - one-net
#my_site
  my_site:
    container_name: my_site
    build:
      context: ./my_site
    image: my_site
    restart: always
    networks:
      - one-net
#storage-server for my_site
  storage:
    container_name: storage
    build:
      context: ./storage
    image: storage
    restart: always
    volumes:
      - my_site_storage:/var/www/storage
    networks:
      - one-net
